console.log(typeof 13)
console.log(typeof 1.3)
console.log(typeof -13)
console.log( 7 + 2)
console.log( 7 - 2)
console.log(typeof( 7 * 2))
console.log(typeof(7 / 2))
console.log(typeof Infinity)
console.log(typeof -Infinity)
console.log(typeof NaN)

